music/urls.py
from django.urls import path
from music import views

app_name = 'music'

urlpatterns = [
    path('', views.home, name='home'),
    path('albums/', views.albums, name='albums'),

]

webapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('music.urls')),
    path('music/', include('music.urls')),
    path('admin/', admin.site.urls),
]

music/models.py
from django.db import models


# Create your models here.
class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.album_title + ' - ' + self.artist

    class Meta:
        verbose_name = 'Album'


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    song_title = models.CharField(max_length=250)
    audio_file = models.FileField(default='')
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

    class Meta:
        verbose_name = 'Song'

music/views.py
from django.shortcuts import render
from .models import Album

# Create your views here.


def home(request):
    return render(request, 'music/home.html', None)


def albums(request):
    albums = Album.objects.all()
    return render(request, 'music/Albums.html', albums)

templates/music/Albums.html
{% extends 'music/base.html' %}
{% block title %}Music{% endblock %}

{% block body %}
    <!-- Album showing -->
    {% for album in albums %}
        <h5>{{ album.title }}</h5>
    {% endfor %}

{% endblock %}

templates/music/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'style/style.css' %}">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
      <title>{% block title %}Title{% endblock %}</title>


  </head>
  <body>

    <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">

  <a class="navbar-brand" href="{% url 'music:home' %}">Karaoke</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'music:albums' %}">Albums</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Songs</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Add Album</a>
      </li>
    </ul>

      <form class="form-inline">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    <ul id="right-content" class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="http://127.0.0.1:8000/admin">Admin</a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="#">Logout</a>
        </li>
    </ul>



  </div>

</nav>
    {% block body %}
    {% endblock %}
  </body>
</html>

templates/music/home.html
{% extends 'music/base.html' %}
{% block title %}Karaoke{% endblock %}

{% block body %}
    <!-- Album showing -->


{% endblock %}